import asyncio

from fastapi import APIRouter, HTTPException, Response

from services.background import background_scrape_job
from services.cache import upstash_get

router = APIRouter()


@router.get("/home")
async def get_home(response: Response):
    response.headers["Cache-Control"] = "public, max-age=3600, stale-while-revalidate=86400"
    try:
        cached = await upstash_get("home_data")
        if cached:
            data = (
                cached.get("data") if isinstance(cached, dict) and "stale_at" in cached else cached
            )
            return {"success": True, "data": data}
        else:
            asyncio.create_task(background_scrape_job())
            return {
                "success": False,
                "message": "Data is being generated by cron job. Please refresh in a minute.",
            }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
