"""Add V3 Gamification and Analytics schemas

Revision ID: 0fe8b395e9a5
Revises: cd9364ff331d
Create Date: 2026-05-08 08:38:55.060591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe8b395e9a5'
down_revision: Union[str, Sequence[str], None] = 'cd9364ff331d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_platform_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_watch_time_sec', sa.Integer(), nullable=True),
    sa.Column('active_users_count', sa.Integer(), nullable=True),
    sa.Column('new_users_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('studios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('anime_characters',
    sa.Column('anilistId', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['anilistId'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anilistId', 'character_id')
    )
    op.create_table('anime_genres',
    sa.Column('anilistId', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anilistId'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anilistId', 'genre_id')
    )
    op.create_table('anime_relations',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_table('anime_studios',
    sa.Column('anilistId', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anilistId'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anilistId', 'studio_id')
    )
    op.create_table('exp_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('exp_gained', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exp_events_user', 'exp_events', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_table('user_genre_affinity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('watch_count', sa.Integer(), nullable=True),
    sa.Column('total_watch_time_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'genre_id', name='uq_user_genre_affinity')
    )
    op.create_table('user_progression',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('total_exp', sa.Integer(), nullable=True),
    sa.Column('current_title_id', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_title_id'], ['titles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_reputation',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reputation')
    op.drop_table('user_progression')
    op.drop_table('user_genre_affinity')
    op.drop_table('user_achievements')
    op.drop_index('idx_exp_events_user', table_name='exp_events')
    op.drop_table('exp_events')
    op.drop_table('anime_studios')
    op.drop_table('anime_relations')
    op.drop_table('anime_genres')
    op.drop_table('anime_characters')
    op.drop_table('titles')
    op.drop_table('studios')
    op.drop_table('genres')
    op.drop_table('daily_platform_metrics')
    op.drop_table('characters')
    op.drop_table('achievements')
    # ### end Alembic commands ###
