"""add_watch_history_table

Revision ID: 652f4316b654
Revises: 6ec1faffeff8
Create Date: 2026-04-19 21:40:31.338019

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "652f4316b654"
down_revision: str | Sequence[str] | None = "6ec1faffeff8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
