"""restore_metadata_and_history

Revision ID: 6ec1faffeff8
Revises: 9503f80bd568
Create Date: 2026-04-19 21:37:54.081852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ec1faffeff8"
down_revision: str | Sequence[str] | None = "9503f80bd568"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anime_metadata", sa.Column("popularity", sa.Integer(), nullable=True))
    op.add_column("anime_metadata", sa.Column("trending", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anime_metadata", "trending")
    op.drop_column("anime_metadata", "popularity")
    # ### end Alembic commands ###
