"""ensure_all_social_tables_v3

Revision ID: 7b315db48a1a
Revises: 652f4316b654
Create Date: 2026-04-19 21:50:00.486806

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b315db48a1a"
down_revision: str | Sequence[str] | None = "652f4316b654"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "watch_history",
        "userId",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "watch_history",
        "animeSlug",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "watch_history",
        "timestampSec",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "watch_history",
        "durationSec",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "watch_history",
        "completed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_constraint(
        op.f("watch_history_userId_animeSlug_episode_unique"), "watch_history", type_="unique"
    )
    op.drop_index(op.f("wh_user_completed_idx"), table_name="watch_history")
    op.drop_index(op.f("wh_user_slug_ep_idx"), table_name="watch_history")
    op.drop_index(op.f("wh_user_updated_at_idx"), table_name="watch_history")
    op.create_unique_constraint(
        "uq_user_anime_history_v2", "watch_history", ["userId", "animeSlug", "episode"]
    )
    op.drop_column("watch_history", "quality")
    op.drop_column("watch_history", "episodeTitle")
    op.drop_column("watch_history", "animeTitle")
    op.drop_column("watch_history", "source")
    op.drop_column("watch_history", "animeCover")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watch_history", sa.Column("animeCover", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "watch_history",
        sa.Column(
            "source",
            sa.TEXT(),
            server_default=sa.text("'oploverz'::text"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "watch_history", sa.Column("animeTitle", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "watch_history", sa.Column("episodeTitle", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "watch_history",
        sa.Column(
            "quality",
            sa.TEXT(),
            server_default=sa.text("'720p'::text"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint("uq_user_anime_history_v2", "watch_history", type_="unique")
    op.create_index(
        op.f("wh_user_updated_at_idx"), "watch_history", ["userId", "updatedAt"], unique=False
    )
    op.create_index(
        op.f("wh_user_slug_ep_idx"),
        "watch_history",
        ["userId", "animeSlug", "episode"],
        unique=False,
    )
    op.create_index(
        op.f("wh_user_completed_idx"),
        "watch_history",
        ["userId", "completed", "updatedAt"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("watch_history_userId_animeSlug_episode_unique"),
        "watch_history",
        ["userId", "animeSlug", "episode"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "watch_history",
        "completed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "watch_history",
        "durationSec",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "watch_history",
        "timestampSec",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "watch_history",
        "animeSlug",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "watch_history",
        "userId",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
