"""Add relations column to anime_metadata

Revision ID: fc18bcc897be
Revises: 0fe8b395e9a5
Create Date: 2026-05-08 09:00:01.694406

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc18bcc897be'
down_revision: str | Sequence[str] | None = '0fe8b395e9a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_metadata', sa.Column('relations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime_metadata', 'relations')
    # ### end Alembic commands ###
