import { NextResponse } from 'next/server';
import { neon } from '@neondatabase/serverless';

export const runtime = 'edge';

export async function POST(request: Request) {
  const adminKey = request.headers.get("x-admin-key");
  if (adminKey !== process.env.ADMIN_API_KEY) {
    return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
  }

  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) {
    return NextResponse.json({ success: false, error: 'DATABASE_URL is not set' }, { status: 500 });
  }

  const sql = neon(dbUrl);

  try {
    const dataResult: any = await sql.query(`
      SELECT id, "anilistId", title, "episodeNumber", "providerId", "episodeUrl", "updatedAt"
      FROM swarm_vault
      ORDER BY "updatedAt" DESC
    `);
    
    const rows = dataResult.rows || dataResult;
    
    const header = ["id", "anilistId", "title", "episodeNumber", "providerId", "episodeUrl", "updatedAt"];
    let csv = header.join(",") + "\n";
    
    for (const r of rows) {
       const rowData = [
         r.id,
         r.anilistId,
         `"${(r.title || 'Unknown').replace(/"/g, '""')}"`,
         r.episodeNumber,
         `"${r.providerId}"`,
         `"${r.episodeUrl}"`,
         r.updatedAt ? r.updatedAt.toISOString() : ""
       ];
       csv += rowData.join(",") + "\n";
    }

    const botToken = process.env.TELEGRAM_BOT_TOKEN;
    const chatId = process.env.TELEGRAM_CHAT_ID;
    
    if (!botToken || !chatId) {
       return NextResponse.json({ success: false, error: "Telegram credentials missing." }, { status: 500 });
    }

    const formData = new FormData();
    formData.append("chat_id", chatId);
    formData.append("caption", `📦 **Swarm Vault Backup**\nTotal Records: ${rows.length}\nAuto-generated by Orca Admin.`);
    
    const fileBlob = new Blob([csv], { type: 'text/csv' });
    formData.append("document", fileBlob, "swarm_vault_backup.csv");

    const tgRes = await fetch(`https://api.telegram.org/bot${botToken}/sendDocument`, {
      method: "POST",
      body: formData
    });

    if (!tgRes.ok) {
       const tgErr = await tgRes.text();
       throw new Error(`Telegram API Error: ${tgErr}`);
    }

    return NextResponse.json({ success: true, message: `Successfully sent ${rows.length} records to Telegram.` });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
